[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["./src/swagger.json"]

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3001

[[redirects]]
  from = "/api-docs/*"
  to = "/.netlify/functions/express-server/api-docs/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/express-server/:splat"
  status = 200